### ISSUE TITLE
About CAN FD

### ISSUE THREAD

**Issue by songapore** [ukign/UDSBoot_G128#1]
Hi, if it is based on the CAN FD bus, what should I modify?

**Comment by ukign** [comment]
Hi,there will be much to be change in networklayer.c and networklayer.h if CAN FD bus is used.
the best way is rewrite these two files, the specification "ISO 15752-2 2016" should be read first.

**Comment by ukign** [comment]
Hi,I commited a new project for CANFD,just a  visual project, realize most of the tranport logic of ISO 15765-2 2016, address"https://github.com/ukign/canfd_tp",for your information.
